backend:
  name: git-gateway # Prod
  repo: recrea-t/campinglamola
  branch: main

local_backend: true

media_folder: static/images
public_folder: /images

site_url: https://www.campinglamola.com
display_url: https://campinglamola.com
logo_url: https://www.campinglamola.com/images/logo.svg

show_preview_links: false

locale: "ca"

collections:
    #Pages
    - name: 'pages-ca'
      label: 'Pàgines (Català)'
      format: frontmatter
      create: false
      delete: false
      editor:
        preview: false
      files:
        - name: 'inici-ca'
          label: Inici
          file: 'src/pages/index.ca.md'
          fields:
            - label: Títol (SEO)
              name: title
              widget: string
            - label: Descripció (SEO)
              name: description
              widget: text
            - label: Imatges
              name: images
              widget: list
              minimize_collapsed: true
              label_singular: imatge
              field: { label: Imatge, name: image, widget: image }
            - label: Descripció
              name: summary
              widget: markdown
            - name: camping
              label: Allotjaments
              widget: list
              summary: "{{fields.title}}"
              allow_add: false
              min: 3
              max: 3
              fields:
                - label: Títol
                  name: title
                  widget: string
                - label: Imatge
                  name: image
                  widget: image
                  allow_multiple: false
            - name: environment
              label: Entorn
              widget: list
              summary: "{{fields.title}}"
              allow_add: false
              min: 3
              max: 3
              fields:
                - label: Títol
                  name: title
                  widget: string
                - label: Imatge
                  name: image
                  widget: image
                  allow_multiple: false
        - name: 'parceles-ca'
          label: 'Parcel·les'
          file: 'src/pages/parceles.ca.md'
          fields:
            - label: Títol (SEO)
              name: title
              widget: string
            - label: Descripció (SEO)
              name: description
              widget: text
            - label: Imatges
              name: images
              widget: list
              minimize_collapsed: true
              label_singular: imatge
              field: { label: Imatge, name: image, widget: image }
            - label: Descripció
              name: summary
              widget: markdown
            - label: Preus
              name: pricing
              widget: list
              fields:
                - label: Nom
                  name: title
                  widget: string
                - label: Resum
                  name: description
                  widget: text
                  required: false
                - label: Preu
                  name: price
                  widget: number
                  value_type: float
                  min: 0
            - label: Normativa
              name: regulation
              widget: markdown
            - label: Condicions
              name: conditions
              widget: markdown
        - name: 'bungalous-ca'
          label: 'Bungalous'
          file: 'src/pages/bungalous.ca.md'
          fields:
            - label: Títol (SEO)
              name: title
              widget: string
            - label: Descripció (SEO)
              name: description
              widget: text
            - label: Imatges
              name: images
              widget: list
              minimize_collapsed: true
              label_singular: imatge
              field: { label: Imatge, name: image, widget: image }
            - label: Descripció
              name: summary
              widget: markdown
            - label: Preus
              name: pricing
              widget: list
              fields:
                - label: Nom
                  name: title
                  widget: string
                - label: Resum
                  name: description
                  widget: text
                  required: false
                - label: Preu temporada alta
                  name: highSeason
                  widget: number
                  value_type: float
                  min: 0
                - label: Preu temporada baixa
                  name: lowSeason
                  widget: number
                  value_type: float
                  min: 0
            - label: Normativa
              name: regulation
              widget: markdown
            - label: Condicions
              name: conditions
              widget: markdown
        - name: 'gaials-ca'
          label: 'Gaials'
          file: 'src/pages/gaials.ca.md'
          fields:
            - label: Títol (SEO)
              name: title
              widget: string
            - label: Descripció (SEO)
              name: description
              widget: text
            - label: Imatges
              name: images
              widget: list
              minimize_collapsed: true
              label_singular: imatge
              field: { label: Imatge, name: image, widget: image }
            - label: Descripció
              name: summary
              widget: markdown
            - label: Preus
              name: pricing
              widget: list
              fields:
                - label: Nom
                  name: title
                  widget: string
                - label: Resum
                  name: description
                  widget: text
                  required: false
                - label: Preu temporada alta
                  name: highSeason
                  widget: number
                  value_type: float
                  min: 0
                - label: Preu temporada baixa
                  name: lowSeason
                  widget: number
                  value_type: float
                  min: 0
            - label: Normativa
              name: regulation
              widget: markdown
            - label: Condicions
              name: conditions
              widget: markdown
        - name: 'services-ca'
          label: 'Serveis'
          file: 'src/pages/serveis.ca.md'
          fields:
            - label: Títol (SEO)
              name: title
              widget: string
            - label: Descripció (SEO)
              name: description
              widget: text
            - label: Imatges
              name: images
              widget: list
              minimize_collapsed: true
              label_singular: imatge
              field: { label: Imatge, name: image, widget: image }
            - name: services
              label: Serveis
              widget: list
              summary: "{{fields.title}}"
              fields:
                - label: Títol
                  name: title
                  widget: string
                - label: Descripció
                  name: description
                  widget: markdown
                  required: false
                - label: Icona
                  name: image
                  widget: image
                  allow_multiple: false
        - name: 'activities-ca'
          label: 'Activitats'
          file: 'src/pages/activitats.ca.md'
          fields:
            - label: Títol (SEO)
              name: title
              widget: string
            - label: Descripció (SEO)
              name: description
              widget: text
            - label: Imatges
              name: images
              widget: list
              minimize_collapsed: true
              label_singular: imatge
              field: { label: Imatge, name: image, widget: image }
            - name: activities
              label: Activitats
              widget: list
              summary: "{{fields.title}}"
              fields:
                - label: Títol
                  name: title
                  widget: string
                - label: Descripció
                  name: description
                  widget: markdown
        - name: 'environment-ca'
          label: Entorn
          file: 'src/pages/entorn.ca.md'
          fields:
            - label: Títol (SEO)
              name: title
              widget: string
            - label: Descripció (SEO)
              name: description
              widget: text
            - label: Imatges
              name: images
              widget: list
              minimize_collapsed: true
              label_singular: imatge
              field: { label: Imatge, name: image, widget: image }
            - label: Descripció
              name: summary
              widget: markdown
            - name: options
              label: Opcions
              widget: list
              summary: "{{fields.title}}"
              min: 3
              fields:
                - label: Títol
                  name: title
                  widget: string
                - label: Descripció
                  name: description
                  widget: markdown
                - label: URL
                  name: url
                  widget: string
                  required: false
        - name: 'contact-ca'
          label: 'Contacte'
          file: 'src/pages/contacte.ca.md'
          fields:
            - label: Títol (SEO)
              name: title
              widget: string
            - label: Descripció (SEO)
              name: description
              widget: text
            - label: Text
              name: summary
              widget: markdown
        - name: 'legal-notice-ca'
          label: 'Avís legal'
          file: 'src/pages/avis-legal.ca.md'
          fields:
            - label: Títol (SEO)
              name: title
              widget: string
            - label: Descripció (SEO)
              name: description
              widget: text
            - label: Cos
              name: body
              widget: markdown
        - name: 'privacy-policy-ca'
          label: 'Protecció de dades'
          file: 'src/pages/proteccio-de-dades.ca.md'
          fields:
            - label: Títol (SEO)
              name: title
              widget: string
            - label: Descripció (SEO)
              name: description
              widget: text
            - label: Cos
              name: body
              widget: markdown
        - name: '404-ca'
          label: '404'
          file: 'src/pages/404.ca.md'
          fields:
            - label: Títol (SEO)
              name: title
              widget: string
            - label: Descripció (SEO)
              name: description
              widget: text
            - label: Cos
              name: body
              widget: markdown
